### ISSUE TITLE
A note about database names

### ISSUE THREAD

**Issue by vegeta897** [airdrummingfool/POSitive-Scripts#1]
In your scripts, where you're inputting database names from the config file, you should change

`use $(positive_db)`

to

`use [$(positive_db)]`

In case the database name happens to be a SQL keyword. I ran into this problem with a database called NATIONAL. It will error out without the brackets indicating an object name.

**Comment by airdrummingfool** [comment]
Thanks for letting me know about this! I've fixed it in all the places I could find; let me know if I missed any occurrences.
